name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the code
      - name: Check out code
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest  # Install pytest for running tests

      # 4. Run tests
      - name: Run tests
        run: |
          pytest --maxfail=5 --disable-warnings --verbose

      # 5. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 6. Build Docker image (Force AMD64)
      - name: Build Docker Image
        run: |
          docker build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/kidney-stone-service:${{ github.sha }} .

      # 7. Push Docker image
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/kidney-stone-service:${{ github.sha }}

      # 8. Tag and push 'latest' if desired
      - name: Tag and Push 'latest'
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/kidney-stone-service:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/kidney-stone-service:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/kidney-stone-service:latest
